# Generated by Django 5.0.3 on 2024-03-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
