# Generated by Django 5.0.3 on 2024-03-10 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0002_remove_books_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='templates/static/images'),
            preserve_default=False,
        ),
    ]
